export default {
  "pay|money|cash": "💸",
  "program|computer|app|compiler|bundler|api|auto|automatically": "🤖",
  idle: "😴",
  "work|development": "🤓",
  "wait|promise": "🕙",
  cool: "😎",
  "modern|fast|blazing|powerful": "🚀",
  "utility|tool|cli|plugin|mod|addon": "🔧",
  between: "↔",
  before: "⬅",
  after: "➡",
  "reload|refresh": "🔁",
  "data|edit|write|ide|editor|code|codebase": "📝",
  id: "💭",
  "react|redux|flux|electron|atom|jsx": "⚛",
  "settings|options|config|cfg|configuration": "⚙",
  "css|style|appearance|stylesheet|look|ui": "💅",
  run: "🏃",
  inject: "💉",
  async: "🔀",
  "npm|package|library": "📦",
  toast: "🍞",
  modal: "ℹ"
};
